name: Android Bootcamp

markdown: redcarpet
highlighter: pygments

paginate: 9
baseurl: /

permalink: /:categories/:title

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
